/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Avatar glade = new Avatar();
        glade.aumentarVida(10);
        glade.aumentarVida(20);
        glade.aumentarVida(10);
        System.out.println(glade.vida);
    }
}
