/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        Carro omega = new Carro();

        omega.acelerar(90);
        omega.acelerar(20);

        System.out.println(omega.obterVelocidadeAtual());

    }
}
