/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {


    public static void main(String[] args) {
        System.out.println("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");

    }

}
