/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Random;

public class App {
    public static void main(String[] args) {
        Random r = new Random();
        int i = r.nextInt(101);
        int tentativas = 0;
        int palpite = 0;
        do {
            palpite = Integer.parseInt(IO.readln("Entre com um número de 1 a 100: "));
            if(palpite > i){
                System.out.println("O palpite é maior");
            }else {
                System.out.println("o palpite é menor");
            }
            tentativas++;
        }while (palpite != i);
        System.out.println("Parabéns você acertou em: " + tentativas);
    }
}
