/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Disciplina poo = new Disciplina();
        poo.obtemCargaHoraria(80);
        System.out.println(poo.cargaHorariaTotal);
    }
}
