/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        int dia = Integer.parseInt(IO.readln("Entre com o dia: "));
        String mes = IO.readln("Entre com o mês: ");
        String estacao = switch (mes) {
                case "janeiro", "fevereiro" ->  "verão";
                case "março" ->  (dia >= 20)? "outono":"verão";
                case "abril", "maio" ->  "outono";
                case "junho" ->  (dia >= 21)? "inverno": "outono";
                case "julho", "agosto" ->  "inverno";
                case "setembro" ->  (dia >= 22)? "primavera": "inverno";
                case "outubro", "novembro" -> "primavera";
                case "dezembro" -> (dia >= 21)? "verão":"primavera";
                default -> "Mês inválido";
            };
        System.out.println(estacao);
    }
}

