/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {


    public static void main(String[] args) {
        Contador contar = new Contador();
        contar.atribuirValor(10);
        contar.incrementar();
        System.out.println(contar.obterValor());
    }
}

