/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.HashMap;

public class App {
    int n = 0;

    public void menu() {
        while (n != 9) {
            n = Integer.parseInt(IO.readln("Entre com a opção desejada"));
            IO.println("Opção 1: Cadastro de livro");
            IO.println("Opção 2: Listar ISBN e Titulo");
            IO.println("Opção 3: Consultar pelo ISBN");
            IO.println("Opção 4: Consultar Pelo Autor");

        }
    }

    private HashMap<String, Livro> livros = new HashMap<>();


    public void cadastrar() {
        String isbn = IO.readln("Entre com o ISBN: ");
        String nome = IO.readln("Entre com o nome do livro: ");
        String autor = IO.readln("Entre com o autor do livro: ");
        String data = IO.readln("Entre com o ano de publicação do livro: ");
        Livro livro = new Livro(isbn, nome, autor, data);
        if (livros.containsKey(isbn)) {
            IO.println("Livro ja cadastrado");
        } else {
            livros.put(isbn, livro);
        }
    }
    public void listarTodos(){
        for (var elemento : livros.entrySet()) {
            System.out.println("ISBN: " + elemento.getKey());
            System.out.println("Título: " + elemento.getValue().getAutor());
        }
    }
    public void consultaIsbn(String isbn){
        System.out.println(livros.get(isbn).getISBN());
        System.out.println(livros.get(isbn).getTitulo());
    }
    public void consultaAutor(String autor){
        if (livros.containsValue(autor)){
             livros.values().equals(autor);
        }else{
            System.out.println("Autor inexistente no cadastro");
        }
    }




    public static void main(String[] args) {

    }


}
