/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Caneta bic = new Caneta("azul", 0.01);
        Caneta faber = new Caneta( 50); //50, azul
        Caneta leoleo = new Caneta(); //100, azul
        bic.setCor("verde");

        System.out.println(bic.desenhar(1,2,1,1));
        System.out.println(bic.toString());
    }
}
