/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        Pessoa aluno = new Pessoa("Glade", "email");
        Pessoa aluno2 = new Pessoa("Guaru", "Guaru@gmail.com");
        Pessoa aluno3 = new Pessoa("Guaru", "Guaru@gmail.com");
        Pessoa aluno4 = new Pessoa("Guaru", "Guaru@gmail.com");

        System.out.println(aluno2.toString());
        /*
        * Criar menu para cadastro de bonecos
        * imprimir tabela bonitinha de pessoas
        * */



    }
}
