/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Batedeira planetaria = new Batedeira();
        //int velocidade = 0;
        String alimento = IO.readln("Entre com um alimento: ");
        if (alimento != null){
            planetaria.aumentaVelocidade();
            System.out.println(planetaria.velocidade);
        }else System.out.println("Sem alimento sem funcionamento!");
    }
}
