/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        String[] triangulo = new String[5];
        int base = Integer.parseInt(args[1]);
        int espaco = base / 2;
        if (args[0].equals("triangulo")) {
            for (int i = 1; i <= base; i++) {
                for (int j = 1; j <= i; j++) {
                    System.out.print("*");
                }
                System.out.println();
            }
        } else if (args[0].equals("losango")) {
            for (int i = 0; i < base; i += 2) {
                if (espaco > 0) {
                    System.out.print(" ".repeat(espaco));
                    espaco--;
                }
                System.out.println("*".repeat((i + 1)));
            }
            espaco = 0;
            for (int i = base - 2 ; i >= 1; i -=2) {
                    espaco++;
                    System.out.print(" ".repeat(espaco));
                System.out.println("*".repeat((i)));
            }
        }
    }
}



/*
 for (int i = 1; i <= base ; i++) {
                    System.out.println(" ");
                    for (int j = 1; j <= i; j++) {
                        System.out.print("*");
                        System.out.print(" ");
                    }
                    System.out.println();
 */