/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.ads;

import java.util.ArrayList;
import java.util.HashMap;

public class App {

    public static void main(String[] args) {
        ArrayList<String> lista = new ArrayList<>();

        /*lista.add("POO");
        lista.add("ADS");
        lista.add("IFSC");
        for (int i = 0; i < lista.size(); i++) {
            System.out.println(lista.get(i));
            System.out.println(" ");
        }
        for(String e : lista){
            System.out.println(e);
        }

        lista.forEach(e -> System.out.println(e));

        lista.forEach(IO::println);

        lista.removeIf(e->e.equals("ADS"));*/

        ArrayList<Pessoa> agenda = new ArrayList<>();

        agenda.add(new Pessoa("Glade", "glade@gmail.com"));
        agenda.add(new Pessoa("Guaru", "guaru@gmail.com"));
        agenda.add(new Pessoa("JVS", "robalorobaloso@gmail.com"));
        agenda.add(new Pessoa("Glade", "glade@gmail.org"));

        agenda.removeIf(p -> p.getNome().equals("Glade"));

        agenda.forEach(IO::println);

        //hashmap
        HashMap<String, String> mapa = new HashMap<>();

        mapa.put("123", "Juca");
        mapa.put("456", "Ana");
        mapa.put("789", "Pedro");
        mapa.put("153", "Juca");
        mapa.put("163", "Juca");

        String nome = mapa.get("789");

        //Duas maneiras de percorer o mapa--------------------------------------------------//
        mapa.forEach((chave, valor)-> IO.println(chave +"  " + valor));

        for (var elemento : mapa.entrySet()){
            System.out.println("chave: " + elemento.getKey());
            System.out.println("valor: " + elemento.getValue());
        }
        //----------------------------------------------------------------------------------//

        //remove pelo id/chave:
        mapa.remove("123");

        //remove pelos valores, não há necessidade de declarar o tipo da variavel("e")
        mapa.values().removeIf(e->e.equals("Juca"));

    }
}
