/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.ads;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        ArrayList<String> lista = new ArrayList<>();

        /*lista.add("POO");
        lista.add("ADS");
        lista.add("IFSC");
        for (int i = 0; i < lista.size(); i++) {
            System.out.println(lista.get(i));
            System.out.println(" ");
        }
        for(String e : lista){
            System.out.println(e);
        }

        lista.forEach(e -> System.out.println(e));

        lista.forEach(IO::println);

        lista.removeIf(e->e.equals("ADS"));*/

        ArrayList<Pessoa> agenda = new ArrayList<>();

        agenda.add(new Pessoa("Glade", "glade@gmail.com"));
        agenda.add(new Pessoa("Guaru", "guaru@gmail.com"));
        agenda.add(new Pessoa("JVS", "robalorobaloso@gmail.com"));
        agenda.add(new Pessoa("Glade", "glade@gmail.org"));

        agenda.removeIf(p -> p.getNome().equals("Glade"));

        agenda.forEach(IO::println);














    }
}
